version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: "redis:6379"
    depends_on:
      - redis
